deploymentMode: "SelectorSyncSet"
selectorSyncSet:
    matchExpressions:
    - key: api.openshift.com/fedramp
      operator: NotIn
      values: ["true"]
    - key: api.openshift.com/managed
      operator: In
      values: ["true"]
    - key: ext-hypershift.openshift.io/cluster-type
      operator: In
      values: ["management-cluster"]
