apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-node-filedescriptor-limit
    role: alert-rules
  name: sre-node-filedescriptor-limit
  namespace: openshift-monitoring
spec:
  groups:
  - name: sre-controlplane-node-almostoutofspace
    rules:
    - alert: ControlPlaneNodeFilesystemAlmostOutOfSpaceSRE
      # This is the same as the upstream alert, but groups by instance id (which is which node is affected)
      # and then only fires on the control-plane, infra, or master node roles
      # See the ocm-agent folder for the WorkerNode version of this alert
      annotations:
        description: Filesystem on {{ $labels.device }} at {{ $labels.instance }}
          has only {{ printf "%.2f" $value }}% available space left.
        runbook_url: https://github.com/openshift/runbooks/blob/master/alerts/cluster-monitoring-operator/NodeFilesystemAlmostOutOfSpace.md
        summary: Filesystem has less than 3% space left.
      expr: |-
        (
          node_filesystem_avail_bytes{job="node-exporter",fstype!="",mountpoint!=""} / node_filesystem_size_bytes{job="node-exporter",fstype!="",mountpoint!=""} * 100 < 3
        and
          node_filesystem_readonly{job="node-exporter",fstype!="",mountpoint!=""} == 0
        )
        * on (instance) group_left () (
          label_replace(kube_node_role{role=~"infra|control-plane|master"}, "instance", "$1", "node", "(.*)")
        )
      for: 30m
      labels:
        severity: critical
        namespace: openshift-monitoring